version: "3.7"

services:
  postgres:
    image: "postgres:15.2"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "spring3jwt"
    volumes:
      - "./postgres.conf:/usr/local/etc/postgres/postgres.conf"
    command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"
    ports:
      - "5432:5432"