spring:
  application:
    name: /security
  main:
    banner-mode: 'OFF'
  datasource:
    url:  ${POSTGRES_JWT_URL:jdbc:postgresql://localhost:5432/jwt_security}
    username: ${POSTGRES_JWT_USERNAME:postgres}
    password: ${POSTGRES_JWT_PASSWORD:spring3jwt}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      enabled: true
      charset: 'UTF-8'
jwt:
  secret: ${JWT_SECRET:5A7134743677397A24432646294A404E635266556A586E327235753878214125}
  expiration-time: ${JWT_EXPIRATION_TIME:600000}